name: Build and Deploy

on:
  push:
    branches: [master, testing-github-action]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        run: bundle install
      - name: Build Jekyll
        run: bundle exec jekyll build --config=_config.yml,_config-prod.yml
      - name: Build SSH Credentials
        run: eval $(ssh-agent -s)
      - name: Build SSH Credentials
        run: echo "${{secrets.SSH_PRIVATE_KEY}}" | tr -d '\r' | ssh-add - > /dev/null
      - name: Send data to the server
        run: rsync -e "ssh -o StrictHostKeyChecking=no" -rvzh ./_site  ${{secrets.ACM_SERVER_USER}}@${{secrets.ACM_SERVER_ADDRESS}}:${{secrets.DEPLOY_PATH}}
