name: Build and Deploy

on:
  push:
    branches: [master, testing-github-action]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        run: bundle install
      - name: Build Jekyll
        run: bundle exec jekyll build --config=_config.yml,_config-prod.yml
      - name: Build SSH Credentials and  Send data to the server
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          ACM_SERVER_ADDRESS: ${{secrets.ACM_SERVER_ADDRESS}}
          ACM_SERVER_USER: ${{secrets.ACM_SERVER_USER}}
          DEPLOY_PATH: ${{secrets.DEPLOY_PATH}}
        run: |
          eval $(ssh-agent -s)
          echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan ${ACM_SERVER_ADDRESS} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          rsync -e "ssh -o StrictHostKeyChecking=no" -rvzh ./_site  ${ACM_SERVER_USER}@${ACM_SERVER_ADDRESS}:${DEPLOY_PATH}
